### ISSUE TITLE
Here is non-mask version (works on Android)

### ISSUE THREAD

**Issue by Noitidart** [TheSavior/react-native-mask-loader#11]
Thanks for the awesome post. I made it with two images, it works in Android. It uses native image uri so images load instantly:

Repo: https://github.com/Noitidart/rn_twitter_loading

### Demo
  * Expo won't have the instant image load, because they dont allow native assets. Here is the snack - https://snack.expo.io/@noitsnack/twitter-loading-no-mask (works in ios too - snack doesnt use the native asset images so image takes a second to load)
    * I don't have my mac readily available right now, but the images need to placed into the native asset folder for this to work, once done, it works to perfection (instant image load) on iOS as well. Would be awesome if someone could PR that, if anyone wants to just try it out without native assets on ios, then just comment out lines 116 and 118, and uncomment out lines 117 and 119 (this is what the snack does).

### How
  * 1st layer is app - https://github.com/Noitidart/rn_twitter_loading/blob/master/App/index.js#L97-L107
  * 2nd layer is 3500px x 3500px blue image with a transparent twitter icon cut out
  * 3rd layer is 3500px x 3500px blue image with the twitter icon filled
  * Images are put in native asset folder so it loads instantly - http://facebook.github.io/react-native/docs/images.html#images-from-hybrid-app-s-resources

### Future
  * Im not great with images so on scale you notice the jagged/blurred eges in the twitter icon/cutout. However i notice that happens in the mask version as well. I tried to make an SVG but failed horribly. If anyone can give me an SVG version for the images this would look perfect.
  * Ideally we make a lib, we take a svg image from a user. Then with react-native-svg we use that to cut out its outline from a background. So dev can just provide a "image" rather then a huge image with a cutout.

**Comment by elicwhite** [comment]
Since this repo is tied to the guide that demonstrates how to do this using a mask, I don't really want to change the project to use a different approach. However, if you want to add a readme to your repo that explains the differences in approach and links to the expo you made then I'd be happy to link to it in the readme of this project. Nice work.

**Comment by Noitidart** [comment]
No problem. Thanks.

I'm very interested in working with someone to do the SVG method. I haven't worked with SVGs before much, so if anyone wants to join me in doing the SVG method that would be great!

SVG skills needed:

* Take a source SVG (for example: twitter icon 64x64) - and then make an outline of it, fill it solid white
* Create a SVG 3500x3500 solid color, and make the middle a solid white version of the source SVG icon
* Create another SVG, 3500x3500 solide color, but cut out the middle of this per the source SVG icon
   * Bonus: background styling like gradients etc
