### ISSUE TITLE
Possible to add StatusBar barStyle prop?

### ISSUE THREAD

**Issue by aaronbentley** [TheSavior/react-native-mask-loader#13]
Hello 👋

I was wondering if its possible to override the [StatusBar barStyle](https://facebook.github.io/react-native/docs/statusbar#barstyle) prop to specify one the valid values for this, i.e 'default', 'light-content', 'dark-content'?

Thanks in advance,

Aaron.

**Comment by elicwhite** [comment]
Are you able to set the color manually outside of this component by rendering the StatusBar component yourself? I believe the values are only overridden when multiple StatusBar components are rendered and the one in this library doesn’t specify a color.

**Comment by aaronbentley** [comment]
Thanks @TheSavior, I have implemented the StatusBar component within my views and it is working as expected. 👍
